### ISSUE TITLE
Index does not seem to be initialised

### ISSUE THREAD

**Issue by stevenwong** [leodagdag/play2-morphia-plugin#10]
Hi,

I have a model with a geo-coordinate index:

```
@Indexed(IndexDirection.GEO2D)
public Double[] coordinate = new Double[2];
```

However, when I check whether the index is there, I get:

```
> db.providers.getIndexes()
[ ]
```

This is because Datastore.ensureIndexes() hasn't been called in MorphiaPlugin (see http://code.google.com/p/morphia/wiki/Datastore#Ensure_Indexes_and_Caps)

Steve

**Comment by leodagdag** [comment]
Hello,
I add call to 

```
ds.ensureIndexes();
ds.ensureCaps();
```

to initialise index and cappedCollection
Thanks for your solution

F.
