### ISSUE TITLE
UNRESOLVED DEPENDENCIES  proxytoys

### ISSUE THREAD

**Issue by fahied** [leodagdag/play2-morphia-plugin#11]
Hi, 

When I try to run yabe example as well installing to new project, I get unresolved dependency error. Would you please tell me how to fix it. I presume the concerned repo is displaced?

Please have a look at below for the whole error log for more information.

Thanks in advance.
Fahied

[warn] problem while downloading module descriptor: http://repo1.maven.org/maven2/com/thoughtworks/proxytoys/proxytoys/1.0/proxytoys-1.0.pom: invalid sha1: expected=bf6942f274dd31a7a2da15cffbe1389cc8e7a84a computed=97693070b018e070dc9aad71946e8324339b7c32 (130ms)
[warn] problem while downloading module descriptor: http://repo1.maven.org/maven2/com/thoughtworks/proxytoys/proxytoys/1.0/proxytoys-1.0.pom: invalid sha1: expected=bf6942f274dd31a7a2da15cffbe1389cc8e7a84a computed=97693070b018e070dc9aad71946e8324339b7c32 (129ms)
[warn]  module not found: com.thoughtworks.proxytoys#proxytoys;1.0
[warn] ==== local: tried
[warn]   /Users/spider/developer/Tools/play-2.0.3/framework/../repository/local/com.thoughtworks.proxytoys/proxytoys/1.0/ivys/ivy.xml
[warn] ==== Typesafe Releases Repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/thoughtworks/proxytoys/proxytoys/1.0/proxytoys-1.0.pom
[warn] ==== Typesafe Snapshots Repository: tried
[warn]   http://repo.typesafe.com/typesafe/snapshots/com/thoughtworks/proxytoys/proxytoys/1.0/proxytoys-1.0.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/thoughtworks/proxytoys/proxytoys/1.0/proxytoys-1.0.pom
[warn] ==== LeoDagDag repository: tried
[warn]   http://leodagdag.github.com/repository/com/thoughtworks/proxytoys/proxytoys/1.0/proxytoys-1.0.pom
[warn] ==== Morphia repository: tried
[warn]   http://morphia.googlecode.com/svn/mavenrepo/com/thoughtworks/proxytoys/proxytoys/1.0/proxytoys-1.0.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/thoughtworks/proxytoys/proxytoys/1.0/proxytoys-1.0.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::  
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.thoughtworks.proxytoys#proxytoys;1.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by stevenwong** [comment]
Not sure how to fix it, but copying proxytoys from my Play 2.0.3 cache to my Play 2.1-snapshot seems to work.

**Comment by chelfe** [comment]
You can disable checksum by putting checksums := Nil into PlayProject settings in Build.scala file.

``` scala
    val appDependencies = Seq(
      // Add your project dependencies here,
        "leodagdag"                         % "play2-morphia-plugin_2.9.1"  % "0.0.6"
    )


    val main = PlayProject(appName, appVersion, appDependencies, mainLang = JAVA)
    .settings(
        resolvers ++= Seq(DefaultMavenRepository, Resolvers.githubRepository, Resolvers.morphiaRepository),
        checksums := Nil
    )


    object Resolvers {
      val githubRepository = "LeoDagDag repository" at "http://leodagdag.github.com/repository/"
      val dropboxRepository = "Dropbox repository" at "http://dl.dropbox.com/u/18533645/repository/"
        val morphiaRepository = "Morphia repository" at "http://morphia.googlecode.com/svn/mavenrepo/"
    }

```

**Comment by leodagdag** [comment]
Hello,
I update release to 0.0.7 and add `checksums := Nil` in Build.scala to avoid problem downloading proxytoys

F.

**Comment by fahied** [comment]
Thanks man. :)
