### ISSUE TITLE
play2-morphia-plugin .asList related Error

### ISSUE THREAD

**Issue by bdeveloper01** [leodagdag/play2-morphia-plugin#2]
Hai!

Model

  public class User extends Model{

   public ObjectId id;
   public String userName;
   public String userType;          //(Admin / Client)
   public boolean canUpdate;  //(true / false)

   @Transient
   public static Model.Finder<ObjectId, User> find = new Model.Finder<ObjectId, User>(ObjectId.class, User.class);

   public static List<User> showAllUsers(){
        return User.find.all();
   }

   public static List<User> showAllAdminUsers(){
        return User.find.filter("userType", "Admin").asList();
   }
   public static List<User> showAllClientUsers(){
        return User.find.filter("userType", "Client").asList();
   }

  }

Controller:-

public class  Application extends Controller {

  public static Result showUser(){
     List<User> user = User.find.showAllUsers();
     System.out.println("All User Count : "+user.size() );
     return null;
  }

  public static Result showAdminUser(){
     List<User> user = User.find.showAllAdminUsers();
     System.out.println("All Admin Count : "+user.size() );
     return null;
  }

  public static Result showClientUsers(){
     List<User> user = User.find.showAllClientUsers();
     System.out.println("All Client Count : "+user.size() );
     return null;
  }

}

---
##  1st time OUT PUT

All User Count : 10
All Admin Count : 5
All Client Count : 5

---
##  2nd time OUT PUT

All User Count : 10
All Admin Count : 1
All Client Count : 1

I don't know why? it is happen.

if you known the reason please help me.
Thanking you!
by
Balamanikandan.T

**Comment by leodagdag** [comment]
Hello,
Could you give me the way you use to fill your data ? or your test class / project ?
Thanks.

F.
