### ISSUE TITLE
play2-morphia-plugin boolean related Error

### ISSUE THREAD

**Issue by bdeveloper01** [leodagdag/play2-morphia-plugin#3]
Hai!

Model

  public class User extends Model{

   public ObjectId id;
   public String userName;
   public String userType;          //(Admin / Client)
   public boolean canUpdate;  //(true / false)

   @Transient
   public static Model.Finder<ObjectId, User> find = new Model.Finder<ObjectId, User>(ObjectId.class, User.class);

   public static List<User> showAllUsers(){
        return User.find.all();
   }

   public static List<User> showAllAdminUsers(){
        return User.find.filter("userType", "Admin").asList();
   }
   public static List<User> showAllClientUsers(){
        return User.find.filter("userType", "Client").asList();
   }

  }

Controller:-

public class  Application extends Controller {

  public static Result showUser(){
     List<User> user = User.find.showAllUsers();
     System.out.println("All User Count : "+user.size() );
     return showAdminUser();
  }

  public static Result showAdminUser(){
     List<User> user = User.find.showAllAdminUsers();
     System.out.println("All Admin Count : "+user.size() );
     return showClientUsers();
  }

  public static Result showClientUsers(){
     List<User> user = User.find.showAllClientUsers();
     System.out.println("All Client Count : "+user.size() );
     return showCanUpdate();
  }

  public static Result showCanUpdate(){
     List<User> user = User.find.filter("userType", "Admin").filter("canUpdate", true).asList();
     System.out.println("All Admin Can Update : "+user.size() );
     return null;
  }

}

---
##  1st time OUT PUT

All User Count : 10
All Admin Count : 5
All Client Count : 5
All Admin Can Update : 0

---
##  2nd time OUT PUT

All User Count : 10
All Admin Count : 1
All Client Count : 1
All Admin Can Update : 0

I don't know why? this Always 0 count. "All Admin Can Update : 0" 

if you known the reason please help me.
Thanking you!
by
Balamanikandan.T

**Comment by leodagdag** [comment]
Hello,
Could you give me the way you use to fill your data ? or your test class / project ?
Thanks.

F.

**Comment by bdeveloper01** [comment]
This is my Upload Script 

package controllers;

import java.io.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import models.User;

public class DataLoader{

```
private static final String Enabled = null;
private static final String Disable = null;

public DataLoader() {
    // TODO Auto-generated constructor stub
}


public boolean isDataLoaded() {
    boolean flag=false;
    try {

        List<User> sp = User.find.all();
             if(sp.isEmpty())
             {
                 flag=true;

             }
             else{
                 flag=false;
             }

    }
    catch (Exception e) {
        // TODO: handle exception
    }
     return flag;
}


public void loadData(InputStream in, String tablename) {

    try {

        if (in != null) {
            InputStreamReader tmp = new InputStreamReader(in);
            BufferedReader reader = new BufferedReader(tmp);
            CSVReader csvreader = new CSVReader(reader, 1);
            String[] nextLine;

            while ((nextLine = csvreader.readNext()) != null) {

                insertdata(nextLine, tablename);

            }

            // setListAdaptor(ar);
        }
    } catch (Exception t) {
    System.out.println(t.toString());
    }
}

public void load()
{
     InputStream in = null;
    // in = this.getClass().getResourceAsStream("SharePolicies.csv");
     try {
     String workingDir = System.getProperty("user.dir");
     workingDir=workingDir+"\\"+"db"+"\\";


    //Users
             in= new FileInputStream(workingDir+"Users.csv");
             System.out.println(in); 
             this.loadData(in,"User");


    } catch (FileNotFoundException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}

public void insertdata(String[] data, String table_name)
        throws ParseException {

     if (table_name.equals("User")) {
            if(data[0]!=null && !data[0].equals(""))
            {               
                User u=new User();
                u.userName=data[0];
                u.userType=data[1];
                if(data[2].trim().toString().equals("True")){
                  u.canUpdate=true;                 
                }else{
                  u.canUpdate=false;
                }                   
                u.insert();
            }                
     }

}
```

}

## Application Controller Index

public static Result index(){
          DataLoader dl=new DataLoader();
          boolean check=dl.isDataLoaded();
          if(check==true)
          {
              dl.load(); 
          }
          else{
               //
          }
return showAllUsers();
}

Thanking you!
by
Balamanikandan.T

**Comment by bdeveloper01** [comment]
Hai!

  Friends do you have get any idea? about this problem.

Thanking you!
by
Balamanikandan.T

**Comment by leodagdag** [comment]
Hello,
Sorry for the delay.
After loading your data, could you check in your database if your data are right ?

In your method 

``` java
public static Result showCanUpdate(){
List user = User.find.filter("userType", "Admin").filter("canUpdate", true).asList();
System.out.println("All Admin Can Update : "+user.size() );
return null;
}
```

your filter for field <code>"userType"</code> with value <code>"Admin"</code>
Do you test your query with mongo client ?

``` javascript
db.User.find({"userType":"Admin","canUpdate":true})
```

F.

**Comment by leodagdag** [comment]
Hello,
Could you try with the new release 0.0.6 and replace the <code>find</code> property of your model with a method <code>find()</code> like describe in issue #8 ?

F.

**Comment by bdeveloper01** [comment]
Hai!

  Thanks for your replay. i will try 0.0.6. I hope you...

Thanking you!
by
Balamanikandan.T

**Comment by bdeveloper01** [comment]
Hai!

  How are you?

  I have some doubt about (new version) how to change my old version to new
version ...

 Do have any tutorial link ... please send to me ...

 Thanking you...

 By
 (bdeveloper01)
 Balamanikandan.T
