### ISSUE TITLE
Thanks for this important fix

### ISSUE THREAD

**Issue by freewind** [leodagdag/play2-morphia-plugin#7]
https://github.com/leodagdag/play2-morphia-plugin/blob/master/src/main/java/leodagdag/play2morphia/MorphiaPlugin.java#L45

```
MorphiaLoggerFactory.reset();
MorphiaLoggerFactory.registerLogger(SLF4JLogrImplFactory.class);
```

That logger issue spent me several hours, until I found your code and article, thank you!

**Comment by leodagdag** [comment]
Your welcome :)
