### ISSUE TITLE
A big issue about Finder

### ISSUE THREAD

**Issue by freewind** [leodagdag/play2-morphia-plugin#8]
The Model#Finder extends `com.google.code.morphia.query.QueryImpl` which is a mutable class (not like the ebean one).

So we can't declare a public static finder instance to reuse it all the time.

For the example you provided, the `Post` class has a finder. If you run:

```
Post.find.filter("_id", new ObjectId("someid"))
```

Then:

```
Post.find.asList
```

You will find the later one only return one instance.

So we have to declare the `find` as:

```
public static Finder find() {
    return new Finder();
}
```

**Comment by leodagdag** [comment]
Thanks for the detected issue and the solution.
