### ISSUE TITLE
morphia-0.0.6 (doubt abut filter)

### ISSUE THREAD

**Issue by bdeveloper01** [leodagdag/play2-morphia-plugin#9]
hai!

  This is my User model

public class User extends Model{

 @Id
 public ObjectId id;

 public String userType; // (Admin / User / Others / Employee)

 ...

```
 public static Model.Finder<ObjectId, User> find()
{
    return new Model.Finder<ObjectId, User>(ObjectId.class, User.class);
}
```

  // I need to filter Admin or User 
 //  how to use Or filter this or that

```
public static List<User> userNameFind(Object userName1)
{
    List<User> nnUser = User.find().filter("Type",  {"Admin"||"User"}).asList();
    return  nnUser;
}
```

}

This is not working
Do you known where i made mistake please guide me...

Thanking you!
by
Balamanikandan.T
(bdeveloper01)

**Comment by leodagdag** [comment]
Hello Balamanikandan,

Sorry for the delay.

To do a query with a OR filter you can see in test case `testFindWithOr`
https://github.com/leodagdag/play2-morphia-plugin/blob/master/src/test/java/leodagdag/play2morphia/ModelTest.java#L104-109

https://github.com/leodagdag/play2-morphia-plugin/blob/master/src/test/java/leodagdag/play2morphia/ModelTest.java#L113-114

F.
